# MIT License
#
# Copyright (c) 2022 Resha Dwika Hefni Al-Fahsi
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ==============================================================================


LR = 1e-4
STEP_LR = 2
N_FFT = 256
N_FFN = 690
N_HEAD = 3
ENC_LAYER = 4
DEC_LAYER = 1
HOP_LENGTH = 80
WIN_LENGTH = 200
BATCH_SIZE = 16
MAX_LEN = 200
EMBED_DIM = 420
EPOCH = 50
START_TOKENID = 2
END_TOKENID = 3
TRAIN_SAVE = "model_pth/"
MAX_SEQ_T = 2754


MODEL_URL = (
    "https://github.com/reshalfahsi/triaxbot/releases/download/pre-v.0.0.0/triaxbot.pth"
)
